name: Build Windows

on: 
    workflow_dispatch:
    workflow_call:
        secrets:
            license:
                required: true

jobs:
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneWindows
          restore-keys: Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.26f1
          targetPlatform: StandaloneWindows
          buildName: StandaloneWindows
          buildsPath: build

      # Output
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: StandaloneWindows
          path: build/StandaloneWindows
