name: Build Mac

on: [workflow_dispatch, workflow_call]

jobs:
  buildWindows:
    name: Build for OSX
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneOSX
          restore-keys: Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.3.26f1
          targetPlatform: StandaloneOSX
          buildName: StandaloneOSX
          buildsPath: build

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: StandaloneOSX
          path: build/StandaloneOSX
