name: Notify Discord Server
on: [workflow_dispatch]
jobs:
  notification:
    name: Notification for new build
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Integration'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
    



