name: Notify Discord Server
on:
    workflow_run:
        workflows: [Build Windows,Build Linux,Build WebGL,Test Workflow]
        types: [completed]
    workflow_dispatch:
env:
    WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    USERNAME: 'Github Integration'
    AVATAR: 'https://pngimg.com/uploads/github/github_PNG40.png '
jobs:
  on-success:
    name: Success Case
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ env.WEBHOOK }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_AVATAR: ${{ env.AVATAR }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
            args: ':white_check_mark: Le build du workflow ${{ github.event.workflow.name }} a réussi ! Plus d`informations sur https://github.com/Dimensions-Softwares/project-destiny/actions '
          
          
  on-failure:
    name: Failure Case
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ env.WEBHOOK }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_AVATAR: ${{ env.AVATAR }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
            args: ':x: Le build du workflow ${{ github.event.workflow_run.workflow.name }} a échoué :( Plus d`informations sur https://github.com/Dimensions-Softwares/project-destiny/actions '
    
  on-dispatch:
    name: Manual Case
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run == null }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ env.WEBHOOK }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_AVATAR: ${{ env.AVATAR }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
            args: ':wrench: Ceci est un test. Si vous voyez ce message c''est que globalement ça marche.'