name: Notify Discord Server
on:
    workflow_run:
        workflows: [Unity Build Actions]
        types:
            -completed
    workflow_dispatch:
jobs:
  on-success:
    name: Success Case
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Integration'
          DISCORD_AVATAR: 'https://logos-download.com/wp-content/uploads/2016/09/GitHub_logo.png'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
            args: ':white_check_mark: Le build a réussi ! Plus d`informations sur https://github.com/Dimensions-Softwares/project-destiny/actions '
          
          
  on-failure:
    name: Failure Case
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Github Integration'
          DISCORD_AVATAR: 'https://logos-download.com/wp-content/uploads/2016/09/GitHub_logo.png'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
            args: ':x: Le build a échoué :( Plus d`informations sur https://github.com/Dimensions-Softwares/project-destiny/actions '