#Le but de ce workflow est de : 
#-Se déclencher quand une pull request est merged vers la branche "main"
#-Lancer les builds auto sur toutes les plateformes
#-Aller chercher le nom du dernier tag sur l'historique de git (chercher ''git tag'' sur google au cas)
#-Créer une release sur Github avec dessus: le tag, le changelog.md et les artifacts générés par les builds

name: Create Release
on: 
    workflow_dispatch:
    pull_request:
        types:
            -closed
        branches:
            - 'main'
jobs:
  #Phase de build
  buildWindows:
    uses: Dimensions-Softwares/project-destiny/.github/workflows/build_windows.yml@feature/DSTNY-21
    
  buildMac:
    uses: Dimensions-Softwares/project-destiny/.github/workflows/build_osx.yml@feature/DSTNY-21
    
  buildLinux:
    uses: Dimensions-Softwares/project-destiny/.github/workflows/build_linux.yml@feature/DSTNY-21
    
  buildWebGL:
    if: ${{ github.event.label.name == 'release' }}
    uses: Dimensions-Softwares/project-destiny/.github/workflows/build_webgl.yml@feature/DSTNY-21
  
  #Enfin on créé la release sur github
  createRelease:
    if: ${{ github.event.label.name == 'release' ||  github.event.label == null}}
    needs: [buildWindows, buildMac, buildLinux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Pour avoir le changelog (y'en a pas pour l'instant mais normalement il devrait être présent à chaque merge de release)
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Get Builds Artifacts #On DL tous les artifacts générés par les builds qui ont été call juste avant
        uses: actions/download-artifact@v2.1.0
        
      - name: Get Previous Tag #On va chercher le dernier tag (qui normalement doit être celui de la release) Pour avoir le numéro de la version
        id: previoustag
        if: ${{ github.event.label.name == 'release' ||  github.event.label == null}}
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
        
      - name: Create Release #On upload le tout sur github
        uses: ncipollo/release-action@v1
        with:
            artifacts: 'StandaloneWindows/*,StandaloneOSX/*,StandaloneLinux64/*'
            bodyFile: 'CHANGELOG.md'
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.previoustag.outputs.tag }}
